/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/mac-draco.glb --output components/3d/MacBook.tsx --types --transform 
Files: public/mac-draco.glb [414.63KB] > C:\Users\Leo\Desktop\perso\dev\project\portfolio\portfolio\components\3d\mac-draco-transformed.glb [63.66KB] (85%)
Enhanced with interactive animations and React Spring integration
*/

'use client'

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
// import { useFrame } from '@react-three/fiber' // removed floating animation
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
// removed '@react-spring/three' import

type GLTFResult = GLTF & {
  nodes: {
    Cube008: THREE.Mesh
    Cube008_1: THREE.Mesh
    Cube008_2: THREE.Mesh
    keyboard: THREE.Mesh
    Cube002: THREE.Mesh
    Cube002_1: THREE.Mesh
    touchbar: THREE.Mesh
  }
  materials: {
    aluminium: THREE.MeshStandardMaterial
    ['matte.001']: THREE.MeshStandardMaterial
    ['screen.001']: THREE.MeshStandardMaterial
    keys: THREE.MeshStandardMaterial
    trackpad: THREE.MeshStandardMaterial
    touchbar: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

interface MacBookModelProps {
  open: boolean
  hinge: number
  position?: [number, number, number]
  rotation?: [number, number, number]
  scale?: number | [number, number, number]
  onClick?: (event: any) => void
  onKeyboardClick?: (event: any) => void
}

export function MacBookModel({ open, hinge, ...props }: MacBookModelProps) {
  const group = useRef<THREE.Group>(null!)
  const { nodes, materials } = useGLTF('/mac-draco.glb') as GLTFResult
  // const [isOpen, setOpen] = useState(open) // removed, rely on parent 'open' only
  
  // Cursor state on hover
  const [hovered, setHovered] = useState(false)
  useEffect(() => {
    document.body.style.cursor = hovered ? 'pointer' : 'auto'
    return () => {
      document.body.style.cursor = 'auto'
    }
  }, [hovered])

  // Handle keyboard click specifically
  const handleKeyboardClick = (event: any) => {
    event.stopPropagation()
    if (props.onKeyboardClick) {
      props.onKeyboardClick(event)
    }
  }

  // Floating/rotation animation removed per request; MacBook stays fixed in place

  return (
    <group 
      ref={group} 
      {...props} position={[0, -5.3, 0]} 
      onPointerOver={(e) => {
        e.stopPropagation()
        setHovered(true)
      }}
      onPointerOut={(e) => setHovered(false)}
      dispose={null}
    >
      {/* Screen/Lid Group with hinge animation */}
      <group rotation={[hinge, 0, 0]} position={[0.002, -0.038, 0.414]} onClick={props.onClick}>
        <group 
          position={[0, 2.965, -0.13]} 
          rotation={[Math.PI / 2, 0, 0]}
        >
          <mesh geometry={nodes.Cube008.geometry} material={materials.aluminium} />
          <mesh geometry={nodes.Cube008_1.geometry} material={materials['matte.001']} />
          <mesh geometry={nodes.Cube008_2.geometry} material={materials['matte.001']} />
        </group>
      </group>
      
      {/* Keyboard */}
      <mesh 
        geometry={nodes.keyboard.geometry} 
        material={materials.keys} 
        position={[1.793, 0, 3.451]} 
        onClick={handleKeyboardClick}
      />
      
      {/* Base/Trackpad Group */}
      <group position={[0, -0.1, 3.394]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.aluminium} />
        <mesh geometry={nodes.Cube002_1.geometry} material={materials.trackpad} />
      </group>
      
      {/* Touchbar */}
      <mesh geometry={nodes.touchbar.geometry} material={materials.touchbar} position={[0, -0.027, 1.201]} />
    </group>
  )
}

useGLTF.preload('/mac-draco.glb')
